USE DB_RESTAURANTE
GO

--INSERTANDO REGISTROS EN LA TABLA CLIENTE

EXEC spInsertarCliente 'ALEX', 'ARHUATA TURPO', 'AV EJERCITO 1050', '923313269'
EXEC spInsertarCliente 'DANIEL', 'GONZALES FRANCO', 'AV INTERNACIONAL 1515', ''
EXEC spInsertarCliente 'JEACKORY', 'LIMA CCOSI', 'AV BOLOGNESI 999', '928396259'
EXEC spInsertarCliente 'JOEL', 'CCALLI CHATA', 'URB SAUCES 1050', '999632152'
EXEC spInsertarCliente 'BRAYAN', 'CONDORI RAMOS', 'CL. GREGORIO ALBARRACIN 510', '948579153'


--INSERTANDO REGISTROS PARA dbo.Tipo_plato
INSERT INTO dbo.Tipo_plato VALUES ('MENU')
INSERT INTO dbo.Tipo_plato VALUES ('A LA CARTA')


--INSERTANDO REGISTROS PARA dbo.Plato
EXEC spInsertarPlato 'HAMBURGUESA EXPRESS CLASICA', 10.9, 1, 'DISPONIBLE';
EXEC spInsertarPlato 'HAMBURGUESA NAPOLITANA', 15.9, 1, 'DISPONIBLE';
EXEC spInsertarPlato 'PIZZA HAWAIANA GRANDE', 33.9, 1, 'DISPONIBLE';


--INSERTANDO REGISTROS PARA USUARIO
INSERT INTO dbo.usuario VALUES ('jeackory_lc','1234','A');
INSERT INTO dbo.usuario VALUES ('alex.arhuata','456','A');
INSERT INTO dbo.usuario VALUES ('calli-joel','789','I');

select * from usuario;